### ISSUE TITLE
CSP Violation

### ISSUE THREAD

**Issue by jason-koon** [Banno/simple-plugin-example#11]
I'm getting a CSP violation loading my test plugin iFrame on garden-fi.com.  It looks like garden-fi.com loads 50+ domains into the allowed frame-src set, but the redirect_uri from my dev dashboard is not on that list.

I see in the docs `The CSP is dynamically updated when Redirect URIs are added to an [External Application](https://jackhenry.dev/open-api-docs/plugins/architecture/externalapplications/).`
https://jackhenry.dev/open-api-docs/plugins/architecture/restrictions/

Does this not apply to the dev dashboard for garden-fi.com?

**Comment by DevWithTheHair** [comment]
@jason-koon normally adding the Redirect URIs should automatically update the CSP.

However, we currently have a bug with JackHenry.Dev-created External Applications not getting picked up as part of the process that updates the CSP.

**Comment by jason-koon** [comment]
@DevWithTheHair  Thanks for the update!
Any idea when I might expect my URI to appear in the CSP?

BTW thanks for the example repos.  Makes getting started very easy!

**Comment by DevWithTheHair** [comment]
@jason-koon thank you!

Also, Engineering has released a fix that should pick up Redirect URIs and add them to the CSP (Content Security Policy). Please try again.

**Comment by jason-koon** [comment]
@DevWithTheHair That fixed it!  Thanks!
